.github/workflows/dco.ml

Disable DCO check for Jane Street organization members

---

.github/workflows/build.yml
.ocamlformat
core/elf.ml
src/perf_tool_backend.ml
src/trace.ml
src/trace_writer.ml
src/tracing_tool_output.ml

Ensure correct formatting in CI

---

README.md

Add GitHub actions build badge

---

src/perf_tool_backend.ml

Include the line of perf output that caused scanf to raise in its error message.

Annotate exceptions while scanning perf output

---

src/trace.ml

Allow tracing all processes when root

---

lib/fzf/src/fzf.ml

Relax `fzf` path resolution

---

core/backend_intf.ml
core/event.ml
core/event.mli
src/import.ml
src/perf_tool_backend.ml
src/trace.ml
src/trace.mli
src/trace_writer.ml
src/trace_writer.mli
test/test.ml

Move a bunch of floating types into modules

---

src/trace.ml

When fzf isn't available in the user's PATH, make the `-pid` argument
mandatory. When it is available, fuzzy find a PID.
Fixes #67.
Test with: `PATH= _build/default/bin/magic_trace_bin.exe attach -output /tmp/x`
Old output:
```
(monitor.ml.Error
(Unix.Unix_error "No such file or directory" execvp
"((prog fzf) (argv (fzf)))")
("Raised at Base__Result.ok_exn in file \"src/result.ml\", line 249, characters 17-26"
"Called from Async_kernel__Deferred1.M.map.(fun) in file \"src/deferred1.ml\", line 17, characters 40-45"
"Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 167, characters 6-47"))
No pid selected
```
New output:
```
The [-pid] argument is mandatory. magic-trace could show you a fuzzy-finding selector here if "fzf" were in your PATH, but it is not.
```

Make fzf an optional runtime dependency

---

src/trace.ml

It had two bugs, which are fixed in this change:
1) When detecting whether or not fzf is avilable, fzf was being invoked
with argv=[--version] instead of argv=[fzf; --version]. That resulted
it in thinking it was invoked without any arguments, which made it
select files.
2) fzf --version was outputting to magic trace's stdout, instead of
being swallowed.

Fix fzf support detection

---

src/perf_tool_backend.ml

Added support for more perf outputs to [Perf_line.to_event] in src/perf_tool_backend.
Simplified the code a bit along the way.
In particular, fixed a bug where any symbol with '=' in it would cause a parse error,
and added a test for this case based on a real program, as well as some more contrived
stress-tests.
I also noticed that traces from the demo Go program (at least sometimes) fail to parse,
so I added some stub code pointing out the problem.
Signed-off-by: Bill Duff <wduff11@gmail.com>

Add support for more perf outputs to [Perf_line.to_event] 

---

README.md
src/trace.ml
src/when_to_snapshot.ml

It brings up fzf, so I think the question mark is a little clearer.
Testing: echo ????hello???? ?

Replace `-trigger $` with `-trigger ?`

---

lib/tracing/demo/tracing_demo.ml
lib/tracing/src/parser.ml
lib/tracing/src/parser.mli
lib/tracing/src/record_writer.ml
lib/tracing/src/trace.ml
lib/tracing/src/trace_intf.ml
lib/tracing/src/util.ml
lib/tracing/src/util.mli
lib/tracing/zero/writer.ml
lib/tracing/zero/writer_intf.ml
src/trace_writer.ml
test/test.ml

Represent pointers as pointers in the Fuchsia trace

---

demo/demo.go

Go code is still a little broken because it has custom control flow when it switches stacks. We'll fix that one day, but not today.

Add an go example that actually works

---

debian/rules

Example run: https://github.com/quantum5/magic-trace/runs/5762575531

Build debian package with flambda

---

.gitignore

Vscode likes to dump trash in my working directory. Please ignore.

Ignore vscode temp files

---

core/perf_map.ml

News to me: perf map files can contain the same address multiple times.
When that happens, take the one that appears later in the file.
I saw this happen with V8. What I think is going on is that it's reusing
address space that old code was JITed into for newly JITed code.

Gracefully handle duplicates in perf map files

---

core/backend_intf.ml
core/timer_resolution.ml
core/timer_resolution.mli
src/import.ml
src/perf_tool_backend.ml
src/trace.ml

Allow specifying timer resolutions

---

README.md
src/tracing_tool_output.ml

We have our own domain now! Woo!

Replace ui.perfetto.dev with magic-trace.org

---

src/perf_tool_backend.ml

Otherwise, under certain circumstances (well-timed ^C, magic-trace
crash), `perf record` remains running on the machine. This is
problematic because there can only be one IPT consumer at a time, so
getting into this state requires realizing there is still a `perf`
process running, and killing it manually.
Ideally we'd do this for the `perf script` invocation too, but I've
punted that as it would require manually doing some `Process` machinery
ourselves, and at least `perf script` is time-bounded, unlike `perf
record`.

Ensure `perf record` process exits when `magic-trace` does

---

.gitignore
.vscode/tasks.json

I use this all the time, figure others might find it useful too.

Add a vscode task to continuously build+test

---

src/breakpoint.ml
src/breakpoint.mli
src/trace_writer.ml

Type breakpoint pid/tids as `Pid.t`

---

src/env_vars.ml
src/env_vars.mli
src/perf_tool_backend.ml

Add escape hatch for `perf` capability checking

---

demo/demo.c

Small tweaks to the C demo before I rebuild the getting started guide.

demo.c: call cos twice, use c99

---

src/trace.ml

- fzf support no longer spews to stderr on failure
- we actually check that the user has perf installed (ubuntu doesn't
do it by default!)

Improve checks for fzf and perf

---

.gitattributes

Thanks to [mananaysiempre](https://news.ycombinator.com/user?id=mananaysiempre) on HN!

Teach linguist about OCaml

---

src/trace.ml

Add `export sexp` command for integrating magic-trace with other tools

---

core/event.mli

Peter pointed this out, but this was unclear without having to read the code what order the callstack list was in and so I felt a doc comment would be well-served here.

Added comment explaining callstack order of Sample event

---

src/perf_decode.ml

I noticed when perf outputs frequencies which are three digits, then the output includes some extra spaces (in two places). I just added some extra logic to the regex to avoid this issue anymore. And I added the failure test case.

Allow extra spacing in cbr regex to not crash on some perf outputs

---

src/env_vars.ml
src/env_vars.mli
src/perf_capabilities.ml
src/perf_tool_backend.ml
src/trace.ml

Add a couple of new environment variables

---

src/perf_capabilities.ml

Reap zombie `perf` processes from capability detection

---

.github/workflows/build-deb.yml
.github/workflows/build.yml
debian/control
src/event.ml
src/event.mli
src/perf_decode.ml
src/trace_writer.ml

Recognize `int3` instructions in trace parser
