janestreet/magic-trace

- .github/workflows/build.yml
Artifacts are attached to successful runs.
Example run: https://github.com/janestreet/magic-trace/actions/runs/1993451400
> Add basic CI to build magic-trace artifacts

- bin/dune
- core/dune
- core/elf.ml
- direct_backend/cinaps/dune
- direct_backend/decoding.ml
- direct_backend/dune
- direct_backend/manual_perf.ml
- dune-project
- lib/src/dune
- lib/test/dune
- src/dune
- src/perf_tool_backend.ml
- src/trace.ml
- src/trace_writer.ml
- test/dune
- test/sample-targets/long-running/dune
- test/sample-targets/long-running/long_running.ml
- test/sample-targets/ocaml-raise/dune
- test/sample-targets/variable-duration/dune
- test/test.ml
Ran `dune build @fmt --auto-promote` to accept changes. There are some
because this code originally was passed through `ocamlformat` and
`ocp-indent`, and we're not going to replicate the precise `ocp-indent`
here.
> Bump to dune 2.0 and set up ocamlformat

- direct_backend/dune
- magic-trace.opam
- test/dune
- test/test.ml
`with` is a trivial internal library that's not public-release'd. Inline
its contents so that tests may build.
Depends on https://github.com/janestreet/magic-trace/pull/11.
> Fix tests depending on internal library

- src/trace.ml
- src/tracing_tool_output.ml
- src/tracing_tool_output.mli
The temporary file path was kind of buggy (e.g. it would output temporary files with XXXXXX in the name). In lieu of actually thinking about that code path and fixing bugs, this feature makes the output
flag mandatory rather than optional.
> Make the output file mandatory.

- src/trace.ml
In the `trace` subcommand, pass signals that would terminate magic-trace on to the child process. This makes it possible to generate traces for executables that loop forever.
> Pass terminating signals to the child process

- core/elf.ml
- src/trace.ml
magic-trace internals already supported running without decodeable
symbol and string tables, it was just the frontend that was disallowing
them. Remove that restriction.
This avoids an uninterpretable error at startup:
(monitor.ml.Error "Option.value_exn None"
("Raised at Base__Error.raise in file \"error.ml\" (inlined), line 9, characters 14-30"
"Called from Base__Option.value_exn in file \"option.ml\", line 105, characters 4-21"
"Called from Magic_trace_lib__Trace.Make_commands.attach_command.(fun) in file \"trace.ml\", line 435, characters 21-67"
"Called from Base__Result.try_with in file \"result.ml\", line 244, characters 9-15"
"Caught by monitor Monitor.protect"))
...and replaces it with a log line of the form:
[Unable to find string or symbol table, will be unable to trigger on …
> Allow running without decodeable debug info

- .github/workflows/dco.ml
> Move .github/workflows/dco.yml to .github/dco.yml

- core/backend_intf.ml
- src/perf_tool_backend.ml
- src/trace_writer.ml
This PR makes magic-trace raise when it sees an unrecognized perf event kind instead of silently ignoring it.
Unrecognized perf events are bugs. Silently ignoring them was a fine idea during initial devleopment of magic-trace, but has quickly fallen off as an optimal strategy as we try to fix the long tail of issues in
different environments.
> Raise on unknown perf event kind

- core/backend_intf.ml
- src/perf_tool_backend.ml
- src/trace_writer.ml
- test/test.ml
Perf uses PID=0 or TID=0 to attach no PID or TID to an event. When it does that, make magic-trace treat them as optional. When it actually goes to write a trace, it now writes a PID/TID of '?'.
Previous behavior was to crash on Pid.of_int if the int was 0.
> Support PIDs and TIDs of 0

- core/backend_intf.ml
- src/trace_writer.ml
All events are known. All events must be known. If we don't know an event, it's a bug.
> Remove the `Unknown` variant for events

- core/backend_intf.ml
- src/perf_tool_backend.ml
- src/trace.ml
- src/trace_writer.ml
- src/tracing_tool_output.ml
- test/test.ml
Kernel addresses have the highest bit set, which means they don't fit in
an OCaml `int`. Also, parsing fails.
Switch to parsing and processing `int64`s. At the boundary to `Tracing`,
truncate to regular `int`s until `Tracing` gains support for `int64`s.
> Add partial support for kernel addresses

- .github/workflows/build.yml
`magic-trace` is a nicer name than `magic_trace_bin.exe`.
> ci: use public name executable

- demo/README.md
- demo/demo.c
- demo/demo.cpp
- demo/demo.go
- demo/demo.js
- demo/demo.ml
- demo/java
These programs are meant to be used with magic trace to quickly test out
whether or not it's working properly. Through varying degrees of
trickery, they can all be run via shebang.
All except the node.js example pipe bytes from /dev/zero to /dev/null.
The node.js example sends HTTP requests to itself. There's no principled
reason why it doesn't do the same thing, I just found HTTP easier deal
with in node than files.
The java demo is just called `java` instead of `demo.java` because
giving it a proper file extension breaks the shebang.
Partially addresses #44. But I don't consider it a complete solution to that
issue. These are demos, but they're not very accessible to people yet.
> Add some example programs

- src/trace.ml
This makes the output much more readable. Fixes #61.
Before:
```
[Attaching to 94060412121401]
```
After:
```
[Attaching to do_read @ 0x0000558c2573b139]
```
> Print symbol name and hex address when using -symbol argument

- .github/workflows/build.yml
This reduced the CI execution time from [>22 minutes](https://github.com/quantum5/magic-trace/actions/runs/2037760651) to [1 minute](https://github.com/quantum5/magic-trace/actions/runs/2037845679).
> Add caching of ~/.opam on CI

- .github/workflows/build.yml
- test/dune
- test/test.ml
In this PR, we:
This should help catch any regressions before they get merged. Fixes #43.
> Run dune runtest in CI

- .github/workflows/build-deb.yml
When a release is created, this PR will make it build the `.deb` package and attach it to the release automatically.
Example: https://github.com/quantum5/magic-trace/releases/tag/v0.0.2-deb-test
Refs #68.
> Upload magic-trace deb package to GitHub releases when tagging

- .github/workflows/build.yml
When a release is created, this PR will make it build the `magic-trace` binary and attach it to the release automatically.
Example: https://github.com/quantum5/magic-trace/releases/tag/binary-upload-test
Refs #68.
> Upload magic-trace binary to GitHub releases when tagging

- README.md
- core/backend_intf.ml
- core/elf.ml
- core/elf.mli
- src/perf_tool_backend.ml
- src/trace.ml
- src/when_to_snapshot.ml
- src/when_to_snapshot.mli
Replace `-symbol` with a "trigger mode" option. To quote my own help
text:
1) If you do not provide `-trigger`, magic-trace takes a snapshot
when either it or the application under trace ends. You can Ctrl+C
magic-trace to manually trigger a snapshot.
2) If you provide `-trigger $`, magic-trace will open up a
fuzzy-find dialog to help you choose a symbol to trace.
3) If you provide `-trigger <FUNCTION NAME>`, magic-trace will
snapshot when the application being traced calls the given
function. This takes the fully-mangled name, so if you're using
anything except C, fuzzy-find mode will probably be easier to
use.
`-trigger .` is a shorthand for `-trigger magic_trace_stop_indicator`.
This also removes three command-line arguments that are, in my opinion,
a mix of unnecessary and probably a …
> Rework trigger modes

- .github/workflows/build.yml
This PR makes the normal build artifact use flambda. To avoid accidentally regressing, the cache key is changed so that the previous non-flambda cache is not used.
Refs #71.
> Build binary with flambda on CI

- core/backend_intf.ml
- core/event.ml
- core/event.mli
- core/trace_mode.ml
- core/trace_mode.mli
- src/import.ml
- src/perf_capabilities.ml
- src/perf_capabilities.mli
- src/perf_tool_backend.ml
- src/trace.ml
- src/trace.mli
- src/trace_writer.ml
- src/trace_writer.mli
- test/test.ml
Some examples below.
Tall ticks are timer interrupts. Short ones are the application under test occasionally performing a read syscall. Timer interrupts occur every 1ms.
Zoomed in on a timer interrupt, they take ~600ns.
Interrupts while running on a core servicing ethernet device interrupts while running `iperf`. Interrupt moderation is visible, with polling ticks ~130us apart.
> Support kernel-mode tracing

- core/elf.ml
- lib/owee/README.md
- lib/owee/examples/decodedline_elf.ml
- lib/owee/examples/decodedline_macho.ml
- lib/owee/src/owee_debug_line.ml
- lib/owee/src/owee_debug_line.mli
- lib/owee/src/owee_elf.ml
- lib/owee/src/owee_elf.mli
- lib/owee/src/owee_form.ml
- lib/owee/src/owee_form.mli
- lib/owee/src/owee_location.ml
This change uses the latest version of owee to implement support for
DWARF 5.
Then dune build magic-trace.
Fixes #2.
This vendors let-def/owee#18.
> Support DWARF 5

- .github/workflows/build.yml
Last time, this failed due to additional complexity introduced by ocaml/setup-ocaml@v2. This complexity is supposed to make our lives better, but it doesn't: it even interferes with our cache, forcing you to use theirs. Except... their cache explicitly doesn't cache our dependencies, so it's still slow. Adding insult to injury, it's also installing more packages from apt, which can't be cached.
Since it's such a pain, we will just do what the v1 did with raw commands, except installing flambda.
Example run without cache: https://github.com/quantum5/magic-trace/runs/5750942329
Example run with cache: https://github.com/quantum5/magic-trace/runs/5751309514
> Build binary with flambda on CI (try 2)

- src/trace_writer.ml
- test/test.ml
This way if they look wonky, the user has an indication as to why.
> Report which frames had start times inferred

- core/trace_mode.ml
- src/perf_tool_backend.ml
- src/trace.ml
- src/tracing_tool_output.ml
- src/tracing_tool_output.mli
- src/when_to_snapshot.ml
Document each argument and refactor the commands a little bit to support
the common pattern [-p $PID].
Fixes #37.
Help text before:
```
Attach to a process and record it until Ctrl-C, then convert the results to a viewable Fuchsia trace.
magic_trace_bin.exe attach
=== flags ===
[-executable-override FILE]
. executable to extract information from, default
is to use the first part of COMMAND
[-full-execution]          . record full program execution
[-http-port PORT]          . http server port
[-multi-snapshot]          . allow taking multiple snapshots if possible
[-multi-thread]            . record multiple threads
[-output FILE]             . output file name (default: 'trace.ftf')
[-perfetto-ui-base-directory PATH]
. path to Perfetto in filesystem
[-pid PID]                 . Process …
```
> Clean up the CLI surface

- src/boot_time.ml
- src/boot_time.mli
- src/boot_time_stubs.c
- src/dune
- src/trace.ml
- src/trace.mli
- test/test.ml
This allows our patched Perfetto viewer to display absolute timestamps.
> Determine and write down base time in trace

- .github/workflows/build.yml
- Makefile
- dune
This commit adds a dune profile called `static`, which forces dune to use static linking by passing `-cclib -static`.
It also creates the opam switch with `ocaml-option-musl` and installs a bunch of musl-compatible kernel headers from `sabotage-linux` on CI so that `core_unix` and the `#include <include/ptrace.h>` in `lib/ocaml-probes` compile.
Example run: https://github.com/quantum5/magic-trace/runs/5764578268
The resulting binaries are tested to run on a `xenial` machine.
Closes #64.
> Build musl statically linked executable on CI

- .github/workflows/build.yml
- debian/rules
As of the recent public-release, it's not necessary any more.
> Remove all references to janestreet-bleeding

- core/backend_intf.ml
- core/decode_result.ml
- core/decode_result.mli
- src/import.ml
- src/perf_tool_backend.ml
- src/trace.ml
- src/trace.mli
- test/test.ml
magic-trace invokes perf twice: once to record a process and once to
turn that record into something magic-trace understands. Both of
those invocations can fail, and we weren't handling that well.
- If `perf record` failed, magic-trace would hang and print nothing
if the error message was long enough.
- If `perf script` failed, magic-trace would just think that there
are no events and not print any message about it.
After applying this change:
- `perf` errors are always forwarded to stderr, and
- if perf returns non-zero, magic-trace returns non-zero.
Testing: Messed up the arguments to the perf calls, one at a time,
and saw that a proper error was printed and that magic-trace
returned non-zero.
Fixes #34 and fixes #38.
> Crash with an error if perf fails

- src/perf_tool_backend.ml
Perf manages to output that kind when someone accidentally types `go run
./demo/demo.go` instead of `./demo/demo.go`. The trace is horribly
broken, but it feels more user-friendly here to show the horribly
broken trace than to crash.
Fixes #80
> Recognize "tr strt tr end"

- core/backend_intf.ml
- src/env_vars.ml
- src/env_vars.mli
- src/perf_tool_backend.ml
- src/trace.ml
- src/tracing_tool_output.ml
This ability was previously configured with a global variable in the
code that requires a rebuild to switch.
I also rework how "verbose" stuff works in magic-trace. Instead of
a single "-v" flag and maybe a "-vv" flag, I opted instead to give the
two verbose flags clear names describing what they do, but start them
with -z- so they sort to the bottom of the argument list.
Also, hide debug commands behind an environment variable to avoid
polluting `-help` with flags that most users don't need.
> Permit printing perf commands from the CLI

- core/event.ml
- core/event.mli
- src/perf_tool_backend.ml
- src/trace_writer.ml
- test/test.ml
Apply Bill's suggested renaming for `Event.t`s fields, and propagate the
new names downstream.
Also, fixed a bug where the `jmp ()` test was testing `Call`, not
`Jump`.
> Add more structure to Event.t

- src/perf_tool_backend.ml
- src/pow2_pages.ml
- src/pow2_pages.mli
Provide a command-line option to tune perf's snapshot buffer size.
This comes with a ton of caveats and I'll have a wiki page up soon
with what it entails.
Testing: I tried a variety of snapshot sizes both with and without
perf_event_paranoid = -1. Warnings and errors were passed upwards
from perf as expected.
Fixes #33
> Make the snapshot buffer size configurable

- .github/workflows/build.yml
This reduces the executable size from ~24 MB to ~3.5 MB, at the cost of increasing the program startup time by 26 ms on my Ryzen 9 5950X.
> Run strip and upx on the executable built by CI

- src/trace.ml
- src/tracing_tool_output.ml
These should feel more familiar for anyone coming over from `perf`.
> Add well-known aliases `-p`/`-o` for `-pid`/`-output`

- core/timer_resolution.ml
- src/perf_tool_backend.ml
We have a proper domain with 301 redirects now. This uses short wiki
links to leave out detail from help text that not all people will
care about. Users that care about the full explaination can follow a
link.
> In help text, provide short links

- src/breakpoint.ml
- src/breakpoint.mli
- src/breakpoint_stubs.c
- src/trace.ml
- src/trace_writer.ml
We don't currently allow putting breakpoints in kernel space, but
the types are nicer now.
Also:
- mark as `Pointer` in Fuchsia trace, so it displays as hex
- mark as `Int64.Hex.t` in `sexp_of` output
> Type breakpoint address as `int64`

- magic-trace.opam
- src/dune
- src/ptrace.ml
- src/ptrace.mli
- src/ptrace_stubs.c
- src/trace.ml
We now do the `ptrace` dance ourselves.
> Drop dependency on `ocaml-probes`

- core/backend_intf.ml
- core/subcommand.ml
- core/subcommand.mli
- src/import.ml
- src/perf_capabilities.ml
- src/perf_capabilities.mli
- src/perf_tool_backend.ml
- src/trace.ml
Tristan mentioned that only relatively recent perfs support
snapshot-at-exit. This feature dynamically detects the user's perf
version and fails with a helpful error if they use an at-exit
trigger mode with an old version of perf.
Technically we say in the wiki that we *require* v5.4+, but I didn't
enforce that anywhere. I figure that if people really want to use
function-triggered snapshotting with an old version of perf, they should
be free to do so.
> Detect when users don't have snapshot-at-exit

- core/event.ml
- core/event.mli
- core/trace_state_change.ml
- core/trace_state_change.mli
- src/import.ml
- src/perf_tool_backend.ml
- src/trace_writer.ml
- test/test.ml
Before this change, they were incorporated into the event kind. This
change splits them out into their own variant so we can think about
them explicitly.
It also has the nice side effect of printing a useful error message
when a user discovers a new kind/trace combination we haven't
previously considered possible.
Testing: The hello-world-with-kernel-tracing test has no diff.
Depends on #145
> Explicitly model start trace / end trace commands

- src/perf_tool_backend.ml
For a particular trace I had on hand, this brings down decode time from
7s to 6s.
Refs #93.
> Speed up hex string parsing

- src/trace_writer.ml
- test/page_fault.ml
A practical, but not perfect, fix for #155: If events happen with
the exact same timestamp as a decode error, stacks break.
Implement a hack to prevent that:
If and only if it doesn't reorder events, pretend the decode
error happened 1ns sooner than it actually did. That makes it have
a distinct timestamp from any following events that have the same
timestamp.
This hack fails, and the user will see broken stacks, when the
previous event has the same timestamp as the overflow error.
I haven't seen that happen before and I imagine it's quite
rare -- it would imply Intel PT was in an overflow state for an
exceedingly small amount of time.
Fixes #155.
Testing: Ran demo.c, got 5 decode errors, and the broken stacks were
fixed. Also, page_fault.ml test replicates this error condition and
it …
> Finesse decode errors back in time by 1ns

- src/trace_writer.ml
- test/page_fault.ml
Instead of moving decode times back by 1ns, it's a little bit cleaner
(and more complete) to move following events forward by 1ns.
Testing: Tests updated how I expect, and also saw a clear trace with
decode error + same tick events following.
> Alternate fix for #115

- src/trace.ml
Closes #144.
---
```
$ ./_build/install/default/bin/magic-trace run --help | head -n50Runs a command and traces it.
magic-trace run COMMAND
=== examples ===
magic-trace run program -- arg1 arg2!
magic-trace run -multi-thread program -- arg1 arg2
magic-trace run -full-execution program
=== flags ===
[-- ARGS]                  . Arguments for the command. Ignored by
magic-trace.
[-full-execution]          . Record a program's full execution instead of
using a snapshot ring buffer.
Warning: The trace grows at a ra
```
---
```
$ ./_build/install/default/bin/magic-trace attach --help | head -n50
Traces a running process.
magic-trace attach 
=== examples ===
magic-trace attach
magic-trace attach -trigger ?
=== flags ===
[-full-execution]          . Record a program's full execution instead of …
```
> Add simple examples to command readmes

- src/perf_tool_backend.ml
This was broken because we passed magic-trace cwd-relative paths, but
also changed the working directory of `perf script`. One of these had to
give, so we no longer run `perf script` inside the working directory.
This matches what we do for `perf record`.
> Fix decoding failure when `-working-dir` is a relative path

- bin/dune
- bin/gen-versions.sh
This PR adds the shell script `bin/gen-versions.sh` which generates an OCaml C stub file containing a strong `generated_hg_version` function which returns the output of `git describe --always --dirty --abbrev=7 --tags`. `core_kernel` will [call this function](https://github.com/janestreet/core_kernel/blob/236a05affa13cfc1a40926f896b883ed024f6a69/version_util/src/version_util.ml#L9-L18) when displaying the version.
Example output: `v0.0.3-56-gfbf5462`
Note that `core_kernel` provides [its own version of this function](https://github.com/janestreet/core_kernel/blob/236a05affa13cfc1a40926f896b883ed024f6a69/version_util/src/version_util_fallback_stubs.c#L12-L15) as a weak symbol, which our version overrides.
We then tell `dune` to generate this stub file by running the shell script and …
> Make --version display git version information

- src/tracing_tool_output.ml
Ideally we'd allow:
- `-serve`: serve on 8080
- `-serve X`: serve on X
- ``: don't serve
...but I don't think `Command.t` can be made to accept this, so I went
back to having a separate `-port` flag.
> Don't unconditionally serve UI if envvar is set

- .github/bug.yml
I propose we land this immediately (assuming you agree with the general idea of having one of these), then make tweaks by clicking the "edit" button on github.
> Add a basic bug-report issue template

- core/event.ml
- core/event.mli
- src/perf_tool_backend.ml
- src/trace_writer.ml
Bill found this when testing a program with the latest magic-trace
> permit IP of 0 when parsing decode errors

- src/breakpoint_stubs.c
This was causing a segfault on every snapshot symbol hit. Yikes.
> Fix int64 breakpoint stub

- src/perf_tool_backend.ml
- src/trace.ml
- Put spaces around square brackets, like perf does
- Do not put warnings in square brackets, again to copy perf
- Use more punctuation
- Prefer periods to exclaimation marks
- Be less specific with how long decoding can take
> Copy edit magic-trace output

- src/perf_tool_backend.ml
I thought SIGINT would work, but it doesn't. I think perf means that it
will take a snapshot when the program under test exits, not when perf
exits...
> Always sigusr2 to take snapshot

- core/timer_resolution.ml
...to match the help text. As an aside, it's pretty confusing for the
default to not be called Normal.
> Make the default timer resolution Normal

- core/backend_intf.ml
- src/perf_tool_backend.ml
- src/trace.ml
This warning isn't very helpful, it's really no big deal if the snapshot
symbol is hit during a full-execution run. This also fixes a minor bug
where the message is printed at the end of every full-execution complete
run because a snapshot is taken at the very end.
> Don't warn when snapshotting during full execution

- core/backend_intf.ml
- src/perf_tool_backend.ml
- src/trace.ml
Make sure snapshotting always happens only once, when we expect it.
In particular, we were snapshotting on exit *and* on trigger symbol
which leads to confusing traces with large [untraced] regions.
Honestly, the real value added by this change is mostly that I
exhaustievly tested snapshotting in all the different ways, including
by simulating a perf that doesn't support snapshot-at-exit.
Testing:
- if perf supports snapshot-at-exit...
- run
[x] snapshot on application exit
[x] snapshot by symbol
[x] snapshot by Ctrl-C
- attach
[x] snapshot by symbol
[x] snapshot on application exit
[x] snapshot by Ctrl-C
- if perf doesn't support snapshot-at-exit...
- run
[.] snapshot on application exit (doesn't work, as expected)
[.] snapshot by Ctrl-C (don't work; expected)
[x] snapshot by symbol
- …
> Rework snapshotting

- .github/workflows/build.yml
- magic-trace.opam
Owee 0.6 has a big speedup to the ELF parsing routine, so `magic-trace`
can pop up `fzf` much quicker now.
> Bump owee to 0.6

- Makefile
For some reason, dune is trying to install the vendored packages. Explicitly specifying that dune install should install magic-trace fixes the build.
Example fixed run: https://github.com/quantum5/magic-trace/runs/6104035999?check_suite_focus=true
> Fix debian package build

- README.md
Moving the gcc linker option `-ldl` later.
With `gcc -ldl demo.c -o demo`, I got: 
```
/usr/bin/ld: /tmp/ccg6cKgo.o: in function `main':
demo.c:(.text+0x30): undefined reference to `dlopen'
/usr/bin/ld: demo.c:(.text+0x40): undefined reference to `dlerror'
/usr/bin/ld: demo.c:(.text+0x6d): undefined reference to `dlerror'
/usr/bin/ld: demo.c:(.text+0x80): undefined reference to `dlsym'
/usr/bin/ld: demo.c:(.text+0x89): undefined reference to `dlerror'
/usr/bin/ld: demo.c:(.text+0x11d): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
```
While `gcc demo.c -ldl -o demo` compiles.
Here's a stackoverflow answer that explains why this is happening:
https://stackoverflow.com/questions/11893996/why-does-the-order-of-l-option-in-gcc-matter/11894098#11894098
> Update README.md: Getting started

- src/perf_tool_backend.ml
Saw this while tracing through self-modifying kernel code.
> Fix parsing of never-ending loop trace errors

- core/elf.ml
- src/trace.ml
- src/trace.mli
- test/test.ml
Owee shouldn't have the ability to crash magic-trace. It's ~always preferably to not display debug info instead of crashing on users.
> Gracefully handle owee failures in Elf.addr_table

- src/trace.ml
- src/tracing_tool_output.ml
- src/tracing_tool_output.mli
> Allow saving raw IPT data to .sexp format, bypassing .fxt generation

- src/trace.ml
This behavior is best demonstrated by the report in #210, where perf
crashed and that made magic-trace crash. Let's nudge people that perf
may have crashed, instead.
Fixes #210
> Give a good error message when waitpid raises

- src/process_info.ml
- src/process_info.mli
- src/trace.ml
- src/trace_writer.ml
- test/test.ml
Addressed #146 in order to give threads a reasonable name. We chose to use the cmdline used to execute the process. This will leave child threads with the original pid + tid name in this case.
Changes:
* Added `Proc_maps` module which allows reading cmdline for any or all PIDs. Reading all was added for later use in #123.
* Updated `thread_writer.ml` to add the cmdline to the naming for each trace. Also made pid/tid more obviously readable.
* Updated Perfetto to display this better. See [here](https://github.com/janestreet/perfetto/pull/24).
> Used procfs to give traced threads more helpful names

- core/backend_intf.ml
- core/dune
- core/perf_map.ml
- core/perf_map.mli
- src/perf_tool_backend.ml
- src/perf_tool_backend.mli
- src/trace.ml
- test/perf_script.ml
This pull request is to add the ability to have a single trace attach to multiple process ids. The interface changes to now allow `-p` to take multiple PIDs as a comma separated list which leaves the interface backward compatible. This is essentially just fed into perf which already supports tracing multiple processes. This feature is only supported by attach and there is not a method for run to run and attach to multiple processes. 
None of the other flags can be specified separately per process, but the trigger point (`-trigger`) is specified on the PID at the head of the list given since this requires the ELF file.
The logic for loading `Perf_map` was changed to allow loading a single map per process ID. For run / decode, a single perf map is still loaded either by filename or by PID.
> Added capability to attach to multiple PIDs for tracing

- core/event.ml
- core/event.mli
- src/perf_tool_backend.ml
- src/perf_tool_backend.mli
- src/real_trace.ml
- src/trace.ml
- src/trace_writer.ml
- src/trace_writer_intf.ml
- test/perf_script.ml
- test/test.ml
Perf already reports CPU frequency through CBR (core-to-bus ratio) events. In this PR, I process these events and create a Counter track in the trace file which will show up in Perfetto. It seems to work as expected and I am able to get the CPU to downclock by using AVX instructions and generally I can see the demo just oscillate close to it's max clock speed.
A few things to note:
- There are two power events that get outputted by perf when I enable them through `perf script`. This gives psb and cbr events. I ignore the psb events (they are a heartbeat like event), but do recognize them along with cbr which we are interested in. I'm not sure if there are examples where CBR events do not give us full information on the CPUs frequency transitions and perf does allow more information to be …
> Added ability to trace CPU frequencies with perf

- core/timer_resolution.ml
- src/perf_tool_backend.ml
Having recognizable URLs inside the help text helps humans and terminal (auto-highlighting) tooling alike
Signed-off-by: Stefan Hoffmeister <stefan.hoffmeister@econos.de>
> Add protocol to URLs embedded in help text

- core/perf_map.ml
- core/util.ml
- core/util.mli
- src/import.ml
- src/perf_decode.ml
This addresses issue #93. Although #150 implemented fast hex string parsing, when I was magic-tracing magic-trace, I noticed this in the trace:
This section of the trace entirely occurs because of calling `Int.Hex.of_string offset` within `parse_symbol_and_offset`. And this tends to take around 200-250 ns. Since this occurs about once per line in the `perf.data` file, the trace I ran this on executed this around 1.8 million times which should save a few hundred ms (out of total time of a few seconds).
Here are the traces after and before this change (respectively) zoomed in on 3 decodes (which shows 3 executions of `parse_symbol_and_offset`) of a perf line containing an entry of the callstack sampled. The former is just below 2 us and the latter is around 2.6 us. However it is clear that …
> Improved speed of hex parsing in more places

- core/event.ml
- core/event.mli
- core/symbol.ml
- core/symbol.mli
- core/symbol_selection.ml
- core/symbol_selection.mli
- core/trace_filter.ml
- core/trace_filter.mli
- core/when_to_snapshot.ml
- core/when_to_snapshot.mli
- src/for_range.ml
- src/for_range.mli
- src/import.ml
- src/trace.ml
- src/trace.mli
- src/trace_writer.ml
- src/trace_writer.mli
- test/perf_script.ml
- test/test.ml
Adds a new flag `-filter "(<start> <stop>)"` to magic trace. With this flag, the trace is trimmed to only include events that occur between `start` (inclusive) and `stop` (exclusive) (#81). If either symbol doesn't appear in the trace, no output is produced. In multi-snapshot mode, the trace only includes regions between consecutive `start` and `stop` calls. The `-filter` flag is compatible with the same modes as the `-trigger` flag.
When producing a `.sexp` output, only events that occur in the filtered region are emitted. When producing a fuchsia `.fxt` output, the full available callstack around the filtered region is reconstructed. Active stack frames at the beginning of the filtered region have the time `start` was called as their inferred start time.
> Filter trace to range

- magic-trace.opam
- src/dune
- src/perf_capabilities.ml
- src/perf_capabilities.mli
- src/perf_dlfilter.c
- src/perf_dlfilter.h
- src/perf_tool_backend.ml
This addresses #32. Since 5.14, perf supports passing `--dlfilter file.so`. This PR creates a filter which skips over any Intel PT events which are branches within the same function. This filter is implemented in `perf_dlfilter.c` and built into `perf_dlfilter.so` by dune and using ocaml-crunch compiled into the ocaml executable for use.
Some things to note:
* There is a custom dune rule which builds the shared object. `ocaml-crunch` was added as a dependency and now to build, `gcc` is also required.
* magic-trace will detect support in `perf_capabilities.ml` for `--dlfilter` by checking the perf version. This ensures compatibility with older perf versions.
* `perf_dlfilter.h` is the include header from perf which is required. It's possible to use the system version, but placing it in …
> Added support to run perf with dlfilter which filters out jumps within same function

- src/env_vars.ml
- src/env_vars.mli
- src/perf_tool_backend.ml
Tudor pointed out the necessity of an environment variable to disable using `--dlfilter` with `perf script`. This is because on our systems, perf is only allowed to run as root and trace the kernel with certain flags which do not include `--dlfilter`. This environment variable will allow the user to forcibly disable `--dlfilter` to be able to still trace the kernel in these situations.
> Added env var to forcibly disable perf dlfilter

- core/backend_intf.ml
- src/callgraph_mode.ml
- src/callgraph_mode.mli
- src/perf_tool_backend.ml
- src/trace.ml
This feature has two changes related to `callgraph_mode`.
* Based on user feedback from #224, I added warnings when the `-callgraph-mode` defaults to either `Dwarf` or `Last_branch_record` to notify the user of potential drawbacks from such selection. These warnings only show if they do not explicitly set the flag.
* Added a fourth option to run with `Last_branch_record { stitched = true }` which calls `perf report --call-graph lbr` and `perf script --stitch-lbr`. There are a few design decisions here though. First I decided to add it as a variant of `Callgraph_mode` for simplicity of interface for the user. However this has the awkward effect of this now being a parameter needed for both decoding and recording (which `Backend_intf` doesn't support). I would think this could perhaps be …
> Added warnings to `-callgraph-mode` and added option for stitched LBR.

- src/perf_decode.ml
magic-trace crashes on the added test case due to missing a space in the regex. This PR just fixes this.
> Fixed regex bug in CBR event when flags includes space

- core/when_to_snapshot.ml
Lee pointed out there is no help message which actually states triggers can only be set within the first PID passed. This PR just adds to the help doc.
> Updated `-trigger` help to specify triggers only apply to first PID passed

- core/backend_intf.ml
- src/perf_tool_backend.ml
- src/trace.ml
This was requested to still allow tools to consume magic-trace output without dlfiltering. Thus when writing events to a sexp file, magic-trace will disable dlfiltering such that all events are outputted. If writing to a fuschia trace file, dlfilter will still be enabled if possible since the events filtered are not useful in the ui.
> Disable dlfilter when printing trace to sexp

- core/dune
- core/elf.ml
- core/elf.mli
- core/elf_intf.ml
- core/symbol_selection.ml
- core/symbol_selection.mli
- core/when_to_snapshot.ml
- src/trace.ml
DRAFT: Rebased on #241.
This feature adds the ability to specify trigger modes like `-trigger line:?` and `-trigger symbol:?` which will cause fzf to only shows files or functions respectively. If `-trigger ?` is passed, it will show both. However if the user selects a file, there is another prompt for them to select the source location to break on.
> Added ability to fuzzy find on line number based triggers

- .github/workflows/build.yml
- .ocamlformat
- core/collection_mode.ml
- core/elf.ml
- core/event.ml
- core/ocaml_exception_info.ml
- core/perf_map.ml
- core/symbol_selection.ml
- core/trace_filter.ml
- core/trace_scope.ml
- core/util.ml
- core/when_to_snapshot.ml
- direct_backend/decoding.ml
- direct_backend/manual_perf.ml
- src/for_range.ml
- src/perf_capabilities.ml
- src/perf_decode.ml
- src/perf_tool_backend.ml
- src/process_info.ml
- src/ptrace.ml
- src/trace.ml
- src/trace_writer.ml
- src/tracing_tool_output.ml
- test/perf_script.ml
- test/sample-targets/long-running/long_running.ml
- test/test.ml
This bumps the version in `.ocamlformat` from 0.21 to 0.23. All the other diffs are a result of changes to how ocamlformat works.
Update: bumped it to the latest version, 0.24.1. This was the source of some of the CI failures.
> .ocamlformat: 0.21 -> 0.24.1

- .github/workflows/build.yml
The old URL disappeared, but this new location appears to work (when I tested it on my personal GitHub repo's CI). I'm not sure how relevant the old comment about musl is -- I didn't investigate deeply. To cover all the bases, I tweaked the comment slightly to just indicate that we're not using the default Ubuntu UPX. I'm guessing the Debian package is just built differently from the Ubuntu equivalent, but, again, didn't investigate too deeply.
> .github/workflows/build.yml: download upx 3.96-2 from ftp.debian.org

- core/demangle_ocaml_symbols.ml
- core/demangle_ocaml_symbols.mli
- core/dune
- core/symbol_selection.ml
- test/demangle_ocaml_symbols.ml
This addresses #82 by implementing the demangling parser from perf. I also included expect tests.
> Demangle OCaml symbols

- core/env_vars.ml
Per #246, I think it's busted right now in the face of trace errors.
Lets turn it off by default until we ship a solution.
> Disable dlfilter by default

- src/trace_writer.ml
In hacky ocaml-exception-detection mode, unwind the stack one more level for caml_stash_backtrace. I did some digging in core_unix and I'm not actually sure when this changed, but traces are stairstep for the following trivial async program without this quick patch.
```ocaml
open! Core
open! Async
let rec go () =
Reader.open_file "a.txt"
>>= fun a ->
Writer.open_file "b.txt"
>>= fun b ->
let p1 = Reader.lines a in
Pipe.iter p1 ~f:(fun line ->
Writer.write_line b line;
Writer.flushed b)
>>= fun () ->
Reader.close a
>>= fun () ->
Writer.close b
>>= fun () ->
Unix.rename ~src:"b.txt" ~dst:"a.txt"
>>= fun () ->
go ()
let command =
Command.async ~summary:"" (Command.Param.return go)
let () =
Command_unix.run command
```
If you run this, you'll need to put some lines of text in a.txt before …
> Unwind the stack for caml_stash_backtrace

- core/symbol_selection.ml
not if symbol is specified by name or defaulted to magic_trace_stop_indicator
Fixes #276.
> Only check for fzf if required to find symbol

- core/elf.ml
The hex string parsing was reversed.
> Fix `-trigger addr:...` selections

- src/trace_writer.ml
- vendor/tracing/zero/writer.ml
- vendor/tracing/zero/writer.mli
Otherwise, the trace writer will raise because we're violating the Perfetto trace file format.
I opted to not show the arguments at all because it was slightly simpler, and it is unlikely the 60-something characters Perfetto would display in the UI would be particularly enlightening for a commandline that's longer than 32 KiB.
Closes https://github.com/janestreet/magic-trace/issues/286.
> Do not display extremely long commandline arguments

- core/event.ml
- core/event.mli
- src/perf_decode.ml
- src/trace_writer.ml
Kernel commit
https://lore.kernel.org/lkml/20230928072953.19369-1-adrian.hunter@intel.com/
set `PERF_IP_FLAG_ASYNC` on trace end events. As per
https://github.com/torvalds/linux/blob/7ee022567bf9e2e0b3cd92461a2f4986ecc99673/tools/perf/builtin-script.c#L1546
I think this means that where `perf` would have previously outputted `tr end  jmp`, it now outputs `tr end  async`.
Adjust our regex to allow `async`, and treat it as a branch.
> Handle `tr end  async` trace events

- src/trace.ml
instead of `magic-trace run prog -- args`.
The current CLI is annoying because you can't just prefix the command line with `magic-trace run`, you have to insert of `--` in between the prog and the args.
I didn't actually run the result, because I get a number of type errors. I fixed enough to know my code types but not everything. Example of what I had to fix:
```diff
diff --git a/src/for_range.ml b/src/for_range.ml
index 5ddf0b0fff...4181efe477 100644
--- a/src/for_range.ml
+++ b/src/for_range.ml
@@ -21,7 +21,7 @@
let range_hit_times ~decode_events ~range_symbols =
let open Deferred.Or_error.Let_syntax in
let%bind { Decode_result.events; _ } = decode_events () in
-  Deferred.List.map events ~f:(fun events ->
+  Deferred.List.map events ~how:`Sequential ~f:(fun events ->
let { …
```
> make it possible to invoke `magic-trace run -- prog args`

- src/perf_tool_backend.ml
We caught this in practice with certain builds of `perf`.
This code seems pretty fishy, and I'd like to look into it further later: it's not obvious to me why `waitpid` would raise if the PID no longer exists. I would have expected `perf` to still be an unreaped child at this point.
But, we do have ~identical logic in ferrying ^C to `perf` in `src/trace.ml` too...
> Don't assume `perf` is still alive after sending it `SIGTERM`

- src/trace.ml
This feels like a hack, but it works for now pending discussion with async devs.
> Restore default SIGINT behavior after taking snapshot

- src/trace_writer.ml
- test/decode_errors.ml
- test/page_fault.ml
Also add more verbose logging for decode errors.
> Be more robust to seeing a poptrap without a matching pushtrap

- .ocamlformat
- core/perf_map.ml
- core/trace_filter.ml
- demo/java
Even though the perf "spec" for jit languages define the perf map syntax, the jcmd Compiler.perfmap insists on prepending 0x to the addresses.
In addition, there's now a way for the jvm to generate the perfmap automatically on exit, making `magic-trace run -multi-thread -snapshot-size 1M -- ./demo/java` return something useful without messing around with perfmap generation. Add these options to the ./demo/java file
> Add support for jcmd Compiler.perfmap

- src/perf_decode.ml
`tx abrt` is treated as a branch, i.e. we do not unwind any callstacks that may have been created during the transaction when it aborts.
This should be sufficient for simple uses of TSX.
Refs #284
> Implement very basic TSX support

- src/trace_writer.ml
We're not going to be able to address all the corner cases any time soon, so in the meantime output exception tracking warnings at most once per trace.
> Reduce noise when OCaml exception tracking gets confused

- src/env_vars.ml
- src/env_vars.mli
- src/event.ml
- src/event.mli
- src/perf_decode.ml
- src/trace_writer.ml
- test/decode_errors.ml
- test/page_fault.ml
- test/test.ml
Add limited support for handling Intel's TSX (Transactional Synchronization Extensions), specifically Restricted Transactional Memory (RTM) where aborted transactions were not properly handled.
This also makes a minor change which corrects error printing, where a flush was intended (%!) but the % accidentally omitted.
> Handle tsx transactions

- magic-trace.opam
- src/elf.ml
Currently symbol resolution on rust binaries returns an address that is 0x1000 above the correct symbol leading to triggers not working.
The current logic seems to assume the symbol value is an offset from the start of the file, but the spec actually states for an executable that this value is a virtual address already: ["In executable and shared object files, st_value holds a virtual address."](https://refspecs.linuxbase.org/elf/gabi4+/ch4.symtab.html#symbol_values)
Most cases can be solved by just picking the first address from the maps file and adding the symbol value to it but there is an edge case where an exotic binary could select a base virtual address that doesn't start at 0x0. This can be detected by reading the program headers and looking at `p_vaddr` for the first `LOAD` …
> Fix symbol resolution for rust binaries
